### PR TITLE
Changed the name and short_name

### PR DESCRIPTION
**Pull request by poojithar23**

### CODE REVIEW

**Comment by dginelsa** [comment]
Looks good. You get a star sticker!

**Review by justinajong — APPROVED** [review]
Gold star!

**Review by dginelsa — APPROVED** [review]

**Review by justinajong — CHANGES_REQUESTED** [review]
"Care Me" should be "**CareMe**". Thanks :P

**Review by justinajong — APPROVED** [review]
I have approved this while I was on vacation lol

**Pull request merged**
